### ISSUE TITLE
Review: Scrapers

### ISSUE THREAD

**Issue by philipmjohnson** [internaloha/internaloha#100]
## Overview

The goal of this review meeting is to get everyone up to speed with the installation of the system, and to do a review of all the scraper code, looking for ways to make it better structured and easier to maintain.

## Review Branch

https://github.com/internaloha/internaloha/tree/review-100/scraper/scrapers

## Files to review

Please review as many of the files as you can in https://github.com/internaloha/internaloha/tree/review-100/scraper/scrapers

## Checklists

* [Design](https://internaloha.github.io/documentation/docs/developers/checklists/design-checklist)
* [JS and ESLint](https://internaloha.github.io/documentation/docs/developers/checklists/js-eslint-checklist)

## Due date

Monday, January 18, 1:30pm

## For more information

The review process is documented at: https://internaloha.github.io/documentation/docs/developers/review/review-process

**Comment by philipmjohnson** [comment]
## Improve the CLI for scraping

We need a "production mode" interface to the scrapers.  That means a single top-level command that (under normal circumstances):

  * Runs any or all of the scripts without opening up a browser.
  * Does not produce any logging output.
  * Does not require a control-c to terminate.
  * Does all necessary post-processing of the data.
  * If there are scrapers that require user input, either fix them or we will deal with them separately.

## Create a top-level interface

We need a top-level interface to all scrapers (for both development and production mode):

  * Each scraper definition file exports a single async function that promises to return a JSON object with the data.
  * A new top-level command (defined in its own file) loops through all scraper definition functions, invoking them, then outside the loop calls Promise.all to wait for all of the results. See https://eslint.org/docs/rules/no-await-in-loop for example code.  This enables all of the scraping to be done in parallel, which could speed things up 10x.
  * Once all of the JSON objects are available, postprocessing is done and final data is written in a UI-ready format.

## Separate utility code from scraper definition code

The scraper/scrapers/ directory currently mixes scraper definition files and files containing utility code. To separate this out, we can have two directories: scraper/scrapers and scraper/util.  Put the utility files in scraper/util.

## Switch from console.log to loglevel

We need a flexible way to provide output for development and debugging that can be disabled easily for production. The best way to do that is to start using a logging package such as https://www.npmjs.com/package/loglevel. Use "silent" for production, and use "trace", "warn", and "error" to categorize output.

## Fix ESLint warnings and errors.

I had to make minor changes to ESLint to make it run, and now it finds many problems.

## Generic issues that afflict most/all scraper definition code

Check for these in all files.  I only noted them the first time I saw them.

 * JS-04: Avoid IIAFE
 * DESIGN-06: UserAgent string should be imported?
 * JS-05: Collapse code onto one line.
 * DESIGN-06: Import fs.writeFile as utility function.
 * DESIGN-08: Modularize long code sections.
 * DESIGN-01: Avoid deeply nested code

## Comments on specific scraper definition files

### acm.js
 * L4?: JS-04: Avoid IIAFE
 * L13?: DESIGN-06: UserAgent string should be imported?
 * L29?: ESLINT-01: Add document as a global var to ESLint to eliminate need for warning.
 * L24: Why loop from 2 to 10? Need a comment.
 * L39: Why not calculate urls.length in for loop declaration?
 * L37: Why not calculate length in for loop declaration (L39)?
 * L43: Why is lastScraped calculated inside the for loop?
 * L48+: JS-03: No console log. Use a logger instead.
 * L96: What if there are more or less than 8 tabs?
 * L103: DESIGN-06: Import fs.writeFile as utility function.

### aexpress.js:
 * L16: JS-05: Collapse code onto one line.
 * L29: DESIGN-03: Eliminate large comment block.

### apple.js
 * L6: DESIGN-06: Import delay() as utility function.

### Glassdoor.js
 * JS-01: File name should not be capitalized.
 * L22: JS-07: Use the ternary operator:
 const daysBack = (posted.includes('h') || posted.includes('hours')) ? 0 : posted.match(/\d+/g);

### idealist.js
 * createDate(): Why is this async? Needs documentation of parameters. Not sure what this is doing.
 * L186+: DESIGN-05: Refactor.

### ihiretechnology.js
 * L31+: DESIGN-03: Eliminate large comment block.

### indeed.js
 * L179, 188: JS-07: ternary operator.

### linkedin.js
 * L19: DESIGN-03: Eliminate large comment block.
 * DESIGN-08: Modularize long code sections

### monster.js
 * L26: DESIGN-03: Eliminate large comment block.
 * L63: JS-06: Don't use try-catch for control flow.

### simplyHired.js:
 * L118: Skills not defined. ESLint does not pass.

### stackoverflow.js, zipRecruiter.js
 * I looked at this briefly, didn't see anything outside of generic issues.

**Comment by jhsuP** [comment]
Repeat code, could add as utility functions:
- Write to file
- Converting date to date time format
- Evaluate --> Array.from(document... ) format
- page set up (setBrowser up, angellist has good example)
- Wait for selector then click...; make sure parameter has option to specify how long to wait before timeout

For all:
- JS-04: Avoid Immediately Invoked Async Function Expressions
- JS-06: Don't use try-catch for control flow
     - Create function to check if selector exists.. 
     - [Ideas](https://github.com/puppeteer/puppeteer/issues/1149)
- DESIGN-08: Modularize long code sections.
     - Break up into separate functions or call from scraperFunctions util
- DESIGN-01: Avoid deeply nested code
- No await in loop
     - Note some awaits in the loop are dependent of each other (eg. click to show something, _then_ scrape info

simplyHired:
- Bunch of commented out code
- await in loop
- Undeclared variable for skills

ACM:
- Lots of comments inline to disable eslint 
- Missing posted

Aexpress:
- Unused autoscroll
- commented out sections
- Posted doesn't return as date time

AngelList:
- playTest function name

Apple:
- Posted doesn't return as date time

Glassdoor:
- Scrapeinfo function confusing

idealist:
- a lot of try/catch used for control flow
- lot of if/else for data push 

iHireTech:
- lots of commented out / old code 

Indeed:
- hasNext = true uses try/catch for control flow

Linkedin:
- Duplicated code for date conversion
- Commented out code

Monster:
- Commented out code block
- nextPage uses try/catch for control flow

Statistics:
- Uses lodash for concat

Ziprecruiter:
- Uses try/catch for control flow

multi-parser:
- Nested statements
- no main

Single-parser:
- Repeated code... could combine with multi-parser (if no args, parse everything. else arg matches the file name (use try/catch to see if name is inputted correctly)

**Comment by Pauline-Peihan-Wu** [comment]
For all files: 

- change console.log
- change try-catch

**Comment by philipmjohnson** [comment]
## Remaining issues in scraper code

- [ ] idealist.js
* Design-08: Modularize long code sections

- [ ] indeed.js
* Design-08: Modularize long code sections

- [ ] linkedin.js
* Design-08: Modularize long code sections

- [ ] monster.js
* Design-08: Modularize long code sections

- [ ] simplyHired.js
* Design-08: Modularize long code sections

- [ ] stackoverflow.js
* Design-08: Modularize long code sections

- [ ] ziprecruiter.js:
* Design-08: Modularize long code sections.
* L112: why main.then()? why not just main() other scrapers?

- [ ] ScraperFunctions.js
* JS-00: Indentation and whitespace (remove whitespace, use // comment if you prefer)
* JS-01: File violates naming conventions.

- [ ] single_parser.js
* JS-00: Indentation and whitespace (remove whitespace, use // comment if you prefer)
* JS-01: File violates naming conventions.

- [ ] Stackoverflow.js
* Design-08: Modularize long code sections
* Design-03: Eliminate large comment blocks
* L112: why main.then()? why not just main() like other scrapers?

- [ ] Statistics.js:
* Consider loops? For example:
```
const counts = { company: 0, contact: 0, ... };
for (field in counts) {
  if (data[field]) {
    counts[field]++;
}
```
There are two other places where a loop would simplify inline code (_.concat, getStatistics).
