### ISSUE TITLE
Don't default Posted and Last Updated to same value

### ISSUE THREAD

**Issue by philipmjohnson** [internaloha/internaloha#134]
Please do work for this task in a branch called issue-134.

There are suspiciously many postings with the same value for Posted and Last Updated:

<img width="1270" alt="Screen Shot 2021-03-01 at 1 16 05 PM" src="https://user-images.githubusercontent.com/290288/109571952-829ae280-7a90-11eb-9c5f-8b9c69c0a584.png">

It seems like Last Updated should always have a value (i.e. when the listing was last scraped).

But Posted could have a value of N/A if it's not available.  Don't default it to Last Updated.

**Comment by jhsuP** [comment]
That happens when the date the internship was posted was the same day we scrape. So the dates actually use different fields.
![image](https://user-images.githubusercontent.com/56209781/109574264-b1ff1e80-7a93-11eb-8fea-893a648587da.png)
