### ISSUE TITLE
Location includes bogus data

### ISSUE THREAD

**Issue by philipmjohnson** [internaloha/internaloha#137]
Please do work for this task in a branch called issue-137.

Location field has bad stuff:

<img width="230" alt="Screen Shot 2021-03-01 at 1 13 41 PM" src="https://user-images.githubusercontent.com/290288/109572384-31d7b980-7a91-11eb-966c-1902727114f0.png">

Please fix. 

Perhaps there should be a checklist of "manual QA" to be done as part of deployment update. This includes checking that the location field has appropriate values.

**Comment by jhsuP** [comment]
Location seems to specifically bug out from the Apple.js scraper so you might have to look at that scraper specifically.
