### ISSUE TITLE
Improve Sort By controller

### ISSUE THREAD

**Issue by philipmjohnson** [internaloha/internaloha#188]
Please do work for this task in a branch called issue-188.

There are several improvements/bug fixes for the Sort-By controller:

## 1. Change controller from drop down to radio buttons

The sort by field is easy to miss in its current form as a drop-down:

<img width="194" alt="Screen Shot 2021-04-05 at 8 56 55 AM" src="https://user-images.githubusercontent.com/290288/113613619-2fff9980-95ed-11eb-94ec-d3b8b7084788.png">

To make it more obvious what the alternatives are, change this to three radio buttons.  Only one is selectable at any given time.

## 2. Clarify meaning of sort options

I understand what "posted" and "company" means for sort date. What does it mean to sort by "internship"?  Do you mean sort by "Title"? 

## 3. Sorting does not work 

Try sorting by Internship, then back to sorting by posting. What you'll discover is:

  * Many "Posted: N/A" internships appear at the front. All the unknown dates should sort to  the end. 
  * Sorting by posting simply doesn't work. Just scroll down and you'll see mixed up ordering. Here's an example:

<img width="940" alt="Screen Shot 2021-04-05 at 9 03 50 AM" src="https://user-images.githubusercontent.com/290288/113614220-eb283280-95ed-11eb-960a-672c63ffee8d.png">

**Comment by ruizaj** [comment]
Buttons changed to radios, and the wording of each filter has been changed to more reflect what each filter does

**Comment by ruizaj** [comment]
The problem where the default filter isn't matching the posted listing occurred again. Will try to fix alongside sorting problems.
