### ISSUE TITLE
Fix errors in console when running locally

### ISSUE THREAD

**Issue by philipmjohnson** [internaloha/internaloha#221]
Please do work for this task in a branch called issue-221.

If you open the browser window when running locally, lots of problems appear:

<img width="1320" alt="Screen Shot 2021-04-28 at 12 17 43 PM" src="https://user-images.githubusercontent.com/290288/116480787-b0e13800-a81d-11eb-88c7-7b80b175aff8.png">

Please investigate and fix.

**Comment by ruizaj** [comment]
I was able to remove all the errors that comes up on start up, but because of how location and search values are handled, they produce new errors upon changes in filters
