### ISSUE TITLE
Implement Content-Based Recommendation System

### ISSUE THREAD

**Issue by jhsuP** [internaloha/internaloha#68]
Please do the work in an issue called rec-sys-initial. For example rec-sys-jh.

For this issue, play around with various techniques to implement a content-based approach. As there is no easy way to split up the implementation, we each can play around with it.

**Comment by philipmjohnson** [comment]
Let's follow the Issue Driven Project Management Guidelines for naming branches. 

The name of this branch should be: issue-068.
